#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# create folders
mkdir -p /config/www/xbackbone/{storage,logs,static}
mkdir -p /config/www/xbackbone/resources/{cache,database,sessions}

# create symlinks
if [[ ! -L "/app/www/public/config.php" ]]; then
    if [[ -f "/app/www/public/config.php" ]]; then
        cp -nR "/app/www/public/config.php" "/config/www/xbackbone/config.php" 2> >(grep -v 'cp: not replacing')
    fi
    rm -rf "/app/www/public/config.php"
    ln -s "/config/www/xbackbone/config.php" "/app/www/public/config.php"
fi

if [[ ! -L "/app/www/public/storage" ]]; then
    if [[ -d "/app/www/public/storage" ]]; then
        cp -nR "/app/www/public/storage" "/config/www/xbackbone/storage" 2> >(grep -v 'cp: not replacing')
    fi
    rm -rf "/app/www/public/storage"
    ln -s "/config/www/xbackbone/storage" "/app/www/public/storage"
fi

if [[ ! -L "/app/www/public/logs" ]]; then
    if [[ -d "/app/www/public/logs" ]]; then
        cp -nR "/app/www/public/logs" "/config/www/xbackbone/logs" 2> >(grep -v 'cp: not replacing')
    fi
    rm -rf "/app/www/public/logs"
    ln -s "/config/www/xbackbone/logs" "/app/www/public/logs"
fi

if [[ ! -L "/app/www/public/resources/cache" ]]; then
    if [[ -d "/app/www/public/resources/cache" ]]; then
        cp -nR "/app/www/public/resources/cache" "/config/www/xbackbone/resources/cache" 2> >(grep -v 'cp: not replacing')
    fi
    rm -rf "/app/www/public/resources/cache"
    ln -s "/config/www/xbackbone/resources/cache" "/app/www/public/resources/cache"
fi

if [[ ! -L "/app/www/public/resources/database" ]]; then
    if [[ -d "/app/www/public/resources/database" ]]; then
        cp -nR "/app/www/public/resources/database" "/config/www/xbackbone/resources/database" 2> >(grep -v 'cp: not replacing')
    fi
    rm -rf "/app/www/public/resources/database"
    ln -s "/config/www/xbackbone/resources/database" "/app/www/public/resources/database"
fi

if [[ ! -L "/app/www/public/resources/sessions" ]]; then
    if [[ ! -L "/app/www/public/resources/sessions" ]]; then
        cp -nR "/app/www/public/resources/sessions" "/config/www/xbackbone/resources/sessions" 2> >(grep -v 'cp: not replacing')
    fi
    rm -rf "/app/www/public/resources/sessions"
    ln -s "/config/www/xbackbone/resources/sessions" "/app/www/public/resources/sessions"
fi

if [[ ! -L "/app/www/public/static/bootstrap" ]]; then
    if [[ ! -L "/app/www/public/static/bootstrap" ]]; then
        cp -nR "/app/www/public/static/bootstrap" "/config/www/xbackbone/static/bootstrap" 2> >(grep -v 'cp: not replacing')
    fi
    rm -rf "/app/www/public/static/bootstrap"
    ln -s "/config/www/xbackbone/static/bootstrap" "/app/www/public/static/bootstrap"
fi

# Log migration messages
if grep -q 'root /app/www/public;' "/config/nginx/site-confs/default.conf"; then
    for dir in /config/www/xbackbone/{app,bin,bootstrap,vendor}; do
        if [[ -d $dir ]]; then
            dirs+=("$dir")
        fi
    done

    for dir in /config/www/xbackbone/resources/{lang,schemas,templates,uploaders}; do
        if [[ -d $dir ]]; then
            dirs+=("$dir")
        fi
    done

    for dir in /config/www/xbackbone/static/{app,clipboardjs,dropzone,fontawesome,highlightjs,images,jquery,plyr}; do
        if [[ -d $dir ]]; then
            dirs+=("$dir")
        fi
    done

    if [[ -n "${dirs[*]}" ]]; then
        echo "**** Legacy files found in /config/www/xbackbone, these can safely be deleted: ****"
        for dir in "${dirs[@]}"; do
            echo "${dir}"
        done
        echo "****"
    fi
fi
# End migration messages

# fix breaking location change from PR5
if [[ $(grep -c "/index.php?\$args =404;" /config/nginx/site-confs/default.conf) -eq 0 ]]; then
    sed -i $'s|/index.php?\$args =404;|/index.php?\$args;|g' /config/nginx/site-confs/default.conf
fi

# permissions
lsiown -R abc:abc \
    /config
